#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap/app.php';

$kernel = new App\Console\Kernel;
$console = new App\Console\Console($app);
$console->setName('Slim PHP Console');

$console->boot($kernel);

$console->run();
